
Debian Security Advisory
========================


DSA-2529-1 python-django -- several vulnerabilities
---------------------------------------------------



Date Reported:
14 Aug 2012
Affected Packages:

[python-django](https://packages.debian.org/src:python-django)

Vulnerable:
Yes
Security database references:
In the Debian bugtracking system: [Bug 683364](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=683364).  
In Mitre's CVE dictionary: [CVE-2012-3442](https://security-tracker.debian.org/tracker/CVE-2012-3442), [CVE-2012-3443](https://security-tracker.debian.org/tracker/CVE-2012-3443), [CVE-2012-3444](https://security-tracker.debian.org/tracker/CVE-2012-3444).  

More information:

Jeroen Dekkers and others reported several vulnerabilities in Django,
a Python Web framework. The Common Vulnerabilities and Exposures
project defines the following issues:


* [CVE-2012-3442](https://security-tracker.debian.org/tracker/CVE-2012-3442)
Two functions do not validate the scheme of a redirect target,
 which might allow remote attackers to conduct cross-site scripting
 (XSS) attacks via a data: URL.
* [CVE-2012-3443](https://security-tracker.debian.org/tracker/CVE-2012-3443)
The ImageField class completely decompresses image data during image
 validation, which allows remote attackers to cause a denial of service
 (memory consumption) by uploading an image file.
* [CVE-2012-3444](https://security-tracker.debian.org/tracker/CVE-2012-3444)
The get\_image\_dimensions function in the image-handling functionality
 uses a constant chunk size in all attempts to determine dimensions,
 which allows remote attackers to cause a denial of service (process
 or thread consumption) via a large TIFF image.


For the stable distribution (squeeze), this problem has been fixed in
version 1.2.3-3+squeeze3.


For the unstable distribution (sid), this problem has been fixed in
version 1.4.1-1.


We recommend that you upgrade your python-django packages.





